// Concern: the SECOND HALF of the function REGISTRY table as data — the `FuncDef` rows from the text/date parity batch (REPT…) through the Math/Trig and Statistical parity batches, the array/spill batch, the Database family (DSUM…DMIN), and ending with the appended Engineering family (CONVERT), continuing registry_a's stable `FuncId` order; split out of func/mod.rs purely to keep each file within the line budget | Non-concern: the `FuncDef` record + lookup/dispatch machinery and the concatenation (func/mod.rs), the first-half rows (func/registry_a.rs), and the function bodies themselves (the per-family func::* submodules) | IO: none — a static data slice
use super::*;

/// The registry rows from the text/date parity batch (`REPT`) through the appended Engineering family
/// (`CONVERT`), continuing [`super::registry_a::ROWS_A`]'s stable `FuncId` order. [`super::FUNCS`]
/// concatenates the two; this slice must stay ordered and contiguous with `ROWS_A`.
pub(crate) const ROWS_B: &[FuncDef] = &[
    // --- Text/date batch P4 (appended so every earlier row keeps its stable FuncId): the string
    //     built-ins REPT PROPER EXACT VALUE CHAR CODE (impls in func/text.rs) and the date/time
    //     built-ins EOMONTH DAYS WEEKDAY WEEKNUM WORKDAY NETWORKDAYS YEARFRAC HOUR MINUTE SECOND TIME
    //     (impls in func/date.rs, reusing the shared 1900 serial↔date maps + leap-bug fidelity). ---
    FuncDef {
        name: "REPT",
        min_args: 2,
        max_args: Some(2),
        eval: rept_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "PROPER",
        min_args: 1,
        max_args: Some(1),
        eval: proper_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "EXACT",
        min_args: 2,
        max_args: Some(2),
        eval: exact_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "VALUE",
        min_args: 1,
        max_args: Some(1),
        eval: value_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "CHAR",
        min_args: 1,
        max_args: Some(1),
        eval: char_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "CODE",
        min_args: 1,
        max_args: Some(1),
        eval: code_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "EOMONTH",
        min_args: 2,
        max_args: Some(2),
        eval: eomonth_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "DAYS",
        min_args: 2,
        max_args: Some(2),
        eval: days_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "WEEKDAY",
        min_args: 1,
        max_args: Some(2),
        eval: weekday_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "WEEKNUM",
        min_args: 1,
        max_args: Some(2),
        eval: weeknum_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "WORKDAY",
        min_args: 2,
        max_args: Some(3),
        eval: workday_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "NETWORKDAYS",
        min_args: 2,
        max_args: Some(3),
        eval: networkdays_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "YEARFRAC",
        min_args: 2,
        max_args: Some(3),
        eval: yearfrac_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2],
    },
    FuncDef {
        name: "HOUR",
        min_args: 1,
        max_args: Some(1),
        eval: hour_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "MINUTE",
        min_args: 1,
        max_args: Some(1),
        eval: minute_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "SECOND",
        min_args: 1,
        max_args: Some(1),
        eval: second_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "TIME",
        min_args: 3,
        max_args: Some(3),
        eval: time_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2],
    },
    // --- Dynamic-array (spill) batch: UNIQUE SORT FILTER SEQUENCE TRANSPOSE (impls in func/spill.rs).
    //     Each RETURNS an `array`, so its value fills a GRID5 range file whose declared range spans >1
    //     coordinate (charlie-model owns the shape/orientation match); they consume arrays WHOLE, so
    //     no `broadcast` positions. Appended so every earlier row keeps its stable FuncId. ---
    FuncDef {
        name: "UNIQUE",
        min_args: 1,
        max_args: Some(3),
        eval: unique_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "SORT",
        min_args: 1,
        max_args: Some(4),
        eval: sort_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "FILTER",
        min_args: 2,
        max_args: Some(3),
        eval: filter_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "SEQUENCE",
        min_args: 1,
        max_args: Some(4),
        eval: sequence_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "TRANSPOSE",
        min_args: 1,
        max_args: Some(1),
        eval: transpose_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    // --- Information batch P5 (appended so every earlier row keeps its stable FuncId; impls in
    //     func/info.rs alongside the v1 ISBLANK/ISNUMBER/ISTEXT/ISERROR/NA/TYPE): the remaining
    //     IS-predicates (ISERR/ISNA/ISLOGICAL/ISNONTEXT), the error-code query ERROR.TYPE, the
    //     number coercer N, the parity tests ISEVEN/ISODD, and the reference-inspecting ISFORMULA.
    //     N/ISEVEN/ISODD PROPAGATE an operand error (they coerce to a number); every other member is
    //     error-TRANSPARENT (it reports on the error). None broadcast: the predicates inspect an
    //     array operand AS an array (never element-wise), and N/ISEVEN/ISODD take a scalar slot. The
    //     lexer accepts `.` in a name, so ERROR.TYPE is one registry row like STDEV.S. ---
    FuncDef {
        name: "N",
        min_args: 1,
        max_args: Some(1),
        eval: n_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "ISERR",
        min_args: 1,
        max_args: Some(1),
        eval: iserr,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "ISNA",
        min_args: 1,
        max_args: Some(1),
        eval: isna,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "ISLOGICAL",
        min_args: 1,
        max_args: Some(1),
        eval: islogical,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "ISNONTEXT",
        min_args: 1,
        max_args: Some(1),
        eval: isnontext,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "ISEVEN",
        min_args: 1,
        max_args: Some(1),
        eval: iseven_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "ISODD",
        min_args: 1,
        max_args: Some(1),
        eval: isodd_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "ERROR.TYPE",
        min_args: 1,
        max_args: Some(1),
        eval: error_type_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "ISFORMULA",
        min_args: 1,
        max_args: Some(1),
        eval: isformula_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    // --- Math/Trig parity batch (appended so every earlier row keeps its stable FuncId). Rounding /
    //     sign / integer extensions (func/math.rs): TRUNC SIGN MROUND CEILING.MATH FLOOR.MATH EVEN ODD
    //     SUMSQ QUOTIENT; the transcendental family (func/trig.rs): PI EXP LN LOG LOG10 SIN COS TAN
    //     ASIN ACOS ATAN ATAN2 SINH COSH TANH RADIANS DEGREES; the integer/combinatorial family
    //     (func/combinatorics.rs): GCD LCM FACT COMBIN; the VOLATILE random family (func/random.rs):
    //     RAND RANDBETWEEN; and the meta-aggregators (func/subtotal.rs): SUBTOTAL AGGREGATE. The scalar
    //     math/trig/combinatorial built-ins BROADCAST every scalar-numeric position (ENG6: an array in a
    //     scalar slot MAPS the call element-wise, like the earlier ABS/ROUND/SQRT rows) — TRUNC/SIGN/
    //     MROUND/QUOTIENT/CEILING.MATH/FLOOR.MATH/EVEN/ODD and the whole transcendental family, plus
    //     FACT/COMBIN. The array-CONSUMING members do NOT broadcast: SUMSQ (SUM's direct-vs-in-range
    //     gather), the variadic GCD/LCM, the SUBTOTAL/AGGREGATE meta-aggregators, and the 0-arity
    //     PI/RAND. RAND/RANDBETWEEN carry `volatile: true` (they read the resolver's entropy seam). The
    //     `.` in a name is lexer-legal, so CEILING.MATH/FLOOR.MATH are one row each, like STDEV.S. ---
    FuncDef {
        name: "TRUNC",
        min_args: 1,
        max_args: Some(2),
        eval: trunc_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "SIGN",
        min_args: 1,
        max_args: Some(1),
        eval: sign_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "MROUND",
        min_args: 2,
        max_args: Some(2),
        eval: mround_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "CEILING.MATH",
        min_args: 1,
        max_args: Some(3),
        eval: ceiling_math_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2],
    },
    FuncDef {
        name: "FLOOR.MATH",
        min_args: 1,
        max_args: Some(3),
        eval: floor_math_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2],
    },
    FuncDef {
        name: "EVEN",
        min_args: 1,
        max_args: Some(1),
        eval: even_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "ODD",
        min_args: 1,
        max_args: Some(1),
        eval: odd_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "SUMSQ",
        min_args: 1,
        max_args: None,
        eval: sumsq,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "QUOTIENT",
        min_args: 2,
        max_args: Some(2),
        eval: quotient_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "PI",
        min_args: 0,
        max_args: Some(0),
        eval: pi_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "EXP",
        min_args: 1,
        max_args: Some(1),
        eval: exp_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "LN",
        min_args: 1,
        max_args: Some(1),
        eval: ln_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "LOG",
        min_args: 1,
        max_args: Some(2),
        eval: log_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "LOG10",
        min_args: 1,
        max_args: Some(1),
        eval: log10_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "SIN",
        min_args: 1,
        max_args: Some(1),
        eval: sin_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "COS",
        min_args: 1,
        max_args: Some(1),
        eval: cos_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "TAN",
        min_args: 1,
        max_args: Some(1),
        eval: tan_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "ASIN",
        min_args: 1,
        max_args: Some(1),
        eval: asin_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "ACOS",
        min_args: 1,
        max_args: Some(1),
        eval: acos_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "ATAN",
        min_args: 1,
        max_args: Some(1),
        eval: atan_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "ATAN2",
        min_args: 2,
        max_args: Some(2),
        eval: atan2_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "SINH",
        min_args: 1,
        max_args: Some(1),
        eval: sinh_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "COSH",
        min_args: 1,
        max_args: Some(1),
        eval: cosh_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "TANH",
        min_args: 1,
        max_args: Some(1),
        eval: tanh_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "RADIANS",
        min_args: 1,
        max_args: Some(1),
        eval: radians_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "DEGREES",
        min_args: 1,
        max_args: Some(1),
        eval: degrees_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "GCD",
        min_args: 1,
        max_args: None,
        eval: gcd_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "LCM",
        min_args: 1,
        max_args: None,
        eval: lcm_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "FACT",
        min_args: 1,
        max_args: Some(1),
        eval: fact_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "COMBIN",
        min_args: 2,
        max_args: Some(2),
        eval: combin_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "RAND",
        min_args: 0,
        max_args: Some(0),
        eval: rand_fn,
        validate: None,
        volatile: true,
        broadcast: &[],
    },
    FuncDef {
        name: "RANDBETWEEN",
        min_args: 2,
        max_args: Some(2),
        eval: randbetween_fn,
        validate: None,
        volatile: true,
        broadcast: &[],
    },
    FuncDef {
        name: "SUBTOTAL",
        min_args: 2,
        max_args: None,
        eval: subtotal_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "AGGREGATE",
        min_args: 3,
        max_args: None,
        eval: aggregate_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    // --- Statistical parity batch (appended so every earlier row keeps its stable FuncId). Split by
    //     sub-family across sibling modules to stay within the per-file line budget: the descriptive
    //     extensions (func/stats_desc.rs) — the "A"-suffix aggregators AVERAGEA/MAXA/MINA, the
    //     alternative means GEOMEAN/HARMEAN, the deviation AVEDEV, the shape moments SKEW/KURT; the
    //     ranking/positional extensions (func/stats_rank.rs) — RANK.EQ (an ALIAS for the core `rank_fn`
    //     like STDEV.S=STDEV), RANK.AVG, the EXCLUSIVE PERCENTILE.EXC/QUARTILE.EXC, PERCENTRANK (+ its
    //     .INC/.EXC spellings), the all-modes array MODE.MULT and the binning array FREQUENCY; the
    //     bivariate regression family (func/stats_reg.rs) — CORREL/RSQ, COVARIANCE.P/S, SLOPE/INTERCEPT,
    //     FORECAST/FORECAST.LINEAR, TREND; and the normal-distribution family (func/stats_dist.rs) —
    //     STANDARDIZE, NORM.DIST/NORMDIST + NORM.INV/NORMINV, NORM.S.DIST/NORMSDIST + NORM.S.INV/NORMSINV.
    //     The `.` in a name is lexer-legal, so the dotted Excel spellings are one row each. None
    //     broadcast: the aggregators/regressors consume their array arguments WHOLE, and MODE.MULT/
    //     FREQUENCY/TREND RETURN an array (a GRID5 range file's value) rather than mapping element-wise. ---
    FuncDef {
        name: "AVERAGEA",
        min_args: 1,
        max_args: None,
        eval: averagea_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "MAXA",
        min_args: 1,
        max_args: None,
        eval: maxa_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "MINA",
        min_args: 1,
        max_args: None,
        eval: mina_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "GEOMEAN",
        min_args: 1,
        max_args: None,
        eval: geomean_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "HARMEAN",
        min_args: 1,
        max_args: None,
        eval: harmean_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "AVEDEV",
        min_args: 1,
        max_args: None,
        eval: avedev_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "SKEW",
        min_args: 1,
        max_args: None,
        eval: skew_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "KURT",
        min_args: 1,
        max_args: None,
        eval: kurt_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "RANK.EQ",
        min_args: 2,
        max_args: Some(3),
        eval: rank_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "RANK.AVG",
        min_args: 2,
        max_args: Some(3),
        eval: rank_avg_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "PERCENTILE.EXC",
        min_args: 2,
        max_args: Some(2),
        eval: percentile_exc_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "QUARTILE.EXC",
        min_args: 2,
        max_args: Some(2),
        eval: quartile_exc_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "PERCENTRANK",
        min_args: 2,
        max_args: Some(3),
        eval: percentrank_inc_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "PERCENTRANK.INC",
        min_args: 2,
        max_args: Some(3),
        eval: percentrank_inc_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "PERCENTRANK.EXC",
        min_args: 2,
        max_args: Some(3),
        eval: percentrank_exc_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "MODE.MULT",
        min_args: 1,
        max_args: None,
        eval: mode_mult_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "FREQUENCY",
        min_args: 2,
        max_args: Some(2),
        eval: frequency_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "CORREL",
        min_args: 2,
        max_args: Some(2),
        eval: correl_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "RSQ",
        min_args: 2,
        max_args: Some(2),
        eval: rsq_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "COVARIANCE.P",
        min_args: 2,
        max_args: Some(2),
        eval: covariance_p_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "COVARIANCE.S",
        min_args: 2,
        max_args: Some(2),
        eval: covariance_s_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "SLOPE",
        min_args: 2,
        max_args: Some(2),
        eval: slope_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "INTERCEPT",
        min_args: 2,
        max_args: Some(2),
        eval: intercept_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "FORECAST",
        min_args: 3,
        max_args: Some(3),
        eval: forecast_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "FORECAST.LINEAR",
        min_args: 3,
        max_args: Some(3),
        eval: forecast_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "TREND",
        min_args: 1,
        max_args: Some(4),
        eval: trend_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "STANDARDIZE",
        min_args: 3,
        max_args: Some(3),
        eval: standardize_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "NORM.DIST",
        min_args: 4,
        max_args: Some(4),
        eval: norm_dist_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "NORMDIST",
        min_args: 4,
        max_args: Some(4),
        eval: normdist_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "NORM.INV",
        min_args: 3,
        max_args: Some(3),
        eval: norm_inv_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "NORMINV",
        min_args: 3,
        max_args: Some(3),
        eval: norminv_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "NORM.S.DIST",
        min_args: 2,
        max_args: Some(2),
        eval: norm_s_dist_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "NORMSDIST",
        min_args: 1,
        max_args: Some(1),
        eval: normsdist_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "NORM.S.INV",
        min_args: 1,
        max_args: Some(1),
        eval: norm_s_inv_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "NORMSINV",
        min_args: 1,
        max_args: Some(1),
        eval: normsinv_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    // --- Date/time parity batch (appended so every earlier row keeps its stable FuncId): the
    //     text->serial readers DATEVALUE/TIMEVALUE (reusing func::text's ISO parsers), the 360-day
    //     count DAYS360, the ISO week ISOWEEKNUM, and the custom-weekend working-day forms
    //     NETWORKDAYS.INTL/WORKDAY.INTL (impls in func/date.rs). ---
    FuncDef {
        name: "DATEVALUE",
        min_args: 1,
        max_args: Some(1),
        eval: datevalue_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "TIMEVALUE",
        min_args: 1,
        max_args: Some(1),
        eval: timevalue_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "DAYS360",
        min_args: 2,
        max_args: Some(3),
        eval: days360_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2],
    },
    FuncDef {
        name: "ISOWEEKNUM",
        min_args: 1,
        max_args: Some(1),
        eval: isoweeknum_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "NETWORKDAYS.INTL",
        min_args: 2,
        max_args: Some(4),
        eval: networkdays_intl_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2],
    },
    FuncDef {
        name: "WORKDAY.INTL",
        min_args: 2,
        max_args: Some(4),
        eval: workday_intl_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2],
    },
    // --- Text parity batch: the CONCATENATE alias (points at CONCAT's `concat_fn`), the split/scan
    //     built-ins TEXTBEFORE TEXTAFTER TEXTSPLIT, CLEAN, T, NUMBERVALUE, UNICHAR UNICODE (impls in
    //     func/text.rs), and the value->text FORMATTERS FIXED DOLLAR (impls in func/text_format.rs,
    //     sharing TEXT's number-format engine). Appended so every earlier row keeps its stable
    //     FuncId. ---
    FuncDef {
        name: "CONCATENATE",
        min_args: 1,
        max_args: None,
        eval: concat_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "TEXTBEFORE",
        min_args: 2,
        max_args: Some(6),
        eval: textbefore_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2, 3, 4, 5],
    },
    FuncDef {
        name: "TEXTAFTER",
        min_args: 2,
        max_args: Some(6),
        eval: textafter_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2, 3, 4, 5],
    },
    FuncDef {
        name: "TEXTSPLIT",
        min_args: 2,
        max_args: Some(6),
        eval: textsplit_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "CLEAN",
        min_args: 1,
        max_args: Some(1),
        eval: clean_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "T",
        min_args: 1,
        max_args: Some(1),
        eval: t_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "NUMBERVALUE",
        min_args: 1,
        max_args: Some(3),
        eval: numbervalue_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2],
    },
    FuncDef {
        name: "UNICHAR",
        min_args: 1,
        max_args: Some(1),
        eval: unichar_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "UNICODE",
        min_args: 1,
        max_args: Some(1),
        eval: unicode_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "FIXED",
        min_args: 1,
        max_args: Some(3),
        eval: fixed_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2],
    },
    FuncDef {
        name: "DOLLAR",
        min_args: 1,
        max_args: Some(2),
        eval: dollar_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    // --- Financial parity batch (v1++): PV MIRR CUMIPMT CUMPRINC SLN SYD DB DDB EFFECT NOMINAL
    //     PDURATION RRI (impls in func/finance.rs). APPENDED here — not inserted beside the earlier
    //     Financial rows — so every existing row keeps its stable FuncId (grouping in the table is
    //     cosmetic; dispatch is by name). PV closes the annuity family; MIRR/CUMIPMT/CUMPRINC extend
    //     the cash-flow group; SLN/SYD/DB/DDB are the depreciation schedule; EFFECT/NOMINAL/PDURATION/
    //     RRI the rate/period converters. All scalar-only (no broadcasting) except MIRR's leading
    //     values RANGE, which — like NPV/IRR — is consumed whole, so no broadcast positions either. ---
    FuncDef {
        name: "PV",
        min_args: 3,
        max_args: Some(5),
        eval: pv_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "MIRR",
        min_args: 3,
        max_args: Some(3),
        eval: mirr_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "CUMIPMT",
        min_args: 6,
        max_args: Some(6),
        eval: cumipmt_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "CUMPRINC",
        min_args: 6,
        max_args: Some(6),
        eval: cumprinc_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "SLN",
        min_args: 3,
        max_args: Some(3),
        eval: sln_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "SYD",
        min_args: 4,
        max_args: Some(4),
        eval: syd_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "DB",
        min_args: 4,
        max_args: Some(5),
        eval: db_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "DDB",
        min_args: 4,
        max_args: Some(5),
        eval: ddb_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "EFFECT",
        min_args: 2,
        max_args: Some(2),
        eval: effect_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "NOMINAL",
        min_args: 2,
        max_args: Some(2),
        eval: nominal_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "PDURATION",
        min_args: 3,
        max_args: Some(3),
        eval: pduration_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "RRI",
        min_args: 3,
        max_args: Some(3),
        eval: rri_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    // --- Logical constants + XOR (appended at the tail so every existing `FuncId` stays stable;
    //     the bare words TRUE/FALSE are boolean LITERALS in the lexer — these are the call forms). ---
    FuncDef {
        name: "TRUE",
        min_args: 0,
        max_args: Some(0),
        eval: true_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "FALSE",
        min_args: 0,
        max_args: Some(0),
        eval: false_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "XOR",
        min_args: 1,
        max_args: None,
        eval: xor_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    // --- Lookup & reference gap-closure (appended at the tail so every existing `FuncId` stays
    //     stable): ADDRESS (an A1/R1C1 address as text; impl in func/lookup.rs) and the array-shaping
    //     family SORTBY/VSTACK/HSTACK/TAKE/DROP/CHOOSECOLS/CHOOSEROWS (each RETURNS an `array` filling a
    //     GRID5 range file; impls in func/spill.rs alongside SORT/UNIQUE/FILTER). None broadcast — they
    //     consume their arrays WHOLE. ---
    FuncDef {
        name: "ADDRESS",
        min_args: 2,
        max_args: Some(5),
        eval: address_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "SORTBY",
        min_args: 2,
        max_args: None,
        eval: sortby_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "VSTACK",
        min_args: 1,
        max_args: None,
        eval: vstack_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "HSTACK",
        min_args: 1,
        max_args: None,
        eval: hstack_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "TAKE",
        min_args: 2,
        max_args: Some(3),
        eval: take_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "DROP",
        min_args: 2,
        max_args: Some(3),
        eval: drop_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "CHOOSECOLS",
        min_args: 2,
        max_args: None,
        eval: choosecols_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "CHOOSEROWS",
        min_args: 2,
        max_args: None,
        eval: chooserows_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    // --- Database family (the `D*` labelled-block filter-and-reduce workhorse) ---
    FuncDef {
        name: "DSUM",
        min_args: 3,
        max_args: Some(3),
        eval: dsum,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "DAVERAGE",
        min_args: 3,
        max_args: Some(3),
        eval: daverage,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "DCOUNT",
        min_args: 3,
        max_args: Some(3),
        eval: dcount,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "DCOUNTA",
        min_args: 3,
        max_args: Some(3),
        eval: dcounta,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "DGET",
        min_args: 3,
        max_args: Some(3),
        eval: dget,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "DMAX",
        min_args: 3,
        max_args: Some(3),
        eval: dmax,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "DMIN",
        min_args: 3,
        max_args: Some(3),
        eval: dmin,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    // --- Engineering family (func/engineering.rs). CONVERT is scalar-only (an array in any of its
    //     three positions is `#VALUE!` via `scalarize`), like the other scalar math built-ins — no
    //     broadcast positions. ---
    FuncDef {
        name: "CONVERT",
        min_args: 3,
        max_args: Some(3),
        eval: convert_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
];
