// Concern: the first half of the FUNCS registry rows | Non-concern: the row type and dispatch (mod.rs owns them), the function bodies | IO: none
use super::*;

/// The registry rows from `SUM` through the Financial-v1 batch (`XIRR`), in stable `FuncId` order.
/// [`super::FUNCS`] concatenates this with [`super::registry_b::ROWS_B`]; the split is a line-budget
/// seam only, so this slice must stay ordered and contiguous with `ROWS_B` (FuncIds are positional).
pub(crate) const ROWS_A: &[FuncDef] = &[
    FuncDef {
        name: "SUM",
        min_args: 1,
        max_args: None,
        eval: sum,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "AVERAGE",
        min_args: 1,
        max_args: None,
        eval: average,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "COUNT",
        min_args: 1,
        max_args: None,
        eval: count,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "IF",
        min_args: 2,
        max_args: Some(3),
        eval: if_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "IFERROR",
        min_args: 2,
        max_args: Some(2),
        eval: iferror,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "AND",
        min_args: 1,
        max_args: None,
        eval: and_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "OR",
        min_args: 1,
        max_args: None,
        eval: or_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "ABS",
        min_args: 1,
        max_args: Some(1),
        eval: abs_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "ROUND",
        min_args: 2,
        max_args: Some(2),
        eval: round_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "SUMIF",
        min_args: 2,
        max_args: Some(3),
        eval: sumif,
        validate: None,
        volatile: false,
        broadcast: &[1],
    },
    FuncDef {
        name: "SUMIFS",
        min_args: 3,
        max_args: None,
        eval: sumifs,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "COUNTIF",
        min_args: 2,
        max_args: Some(2),
        eval: countif,
        validate: None,
        volatile: false,
        broadcast: &[1],
    },
    FuncDef {
        name: "COUNTIFS",
        min_args: 2,
        max_args: None,
        eval: countifs,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "AVERAGEIF",
        min_args: 2,
        max_args: Some(3),
        eval: averageif,
        validate: None,
        volatile: false,
        broadcast: &[1],
    },
    FuncDef {
        name: "AVERAGEIFS",
        min_args: 3,
        max_args: None,
        eval: averageifs,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "MINIFS",
        min_args: 3,
        max_args: None,
        eval: minifs,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "MAXIFS",
        min_args: 3,
        max_args: None,
        eval: maxifs,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "PRODUCT",
        min_args: 1,
        max_args: None,
        eval: product,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "SUMPRODUCT",
        min_args: 1,
        max_args: None,
        eval: sumproduct,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "ROUNDUP",
        min_args: 2,
        max_args: Some(2),
        eval: roundup,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "ROUNDDOWN",
        min_args: 2,
        max_args: Some(2),
        eval: rounddown,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "INT",
        min_args: 1,
        max_args: Some(1),
        eval: int_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "MOD",
        min_args: 2,
        max_args: Some(2),
        eval: mod_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "POWER",
        min_args: 2,
        max_args: Some(2),
        eval: power_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "SQRT",
        min_args: 1,
        max_args: Some(1),
        eval: sqrt_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "CEILING",
        min_args: 2,
        max_args: Some(2),
        eval: ceiling_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "FLOOR",
        min_args: 2,
        max_args: Some(2),
        eval: floor_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "MIN",
        min_args: 1,
        max_args: None,
        eval: min_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "MAX",
        min_args: 1,
        max_args: None,
        eval: max_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "MEDIAN",
        min_args: 1,
        max_args: None,
        eval: median_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "RANK",
        min_args: 2,
        max_args: Some(3),
        eval: rank_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "COUNTA",
        min_args: 1,
        max_args: None,
        eval: counta,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "COUNTBLANK",
        min_args: 1,
        max_args: Some(1),
        eval: countblank,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "STDEV",
        min_args: 1,
        max_args: None,
        eval: stdev_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "STDEV.S",
        min_args: 1,
        max_args: None,
        eval: stdev_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "STDEVP",
        min_args: 1,
        max_args: None,
        eval: stdevp_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "STDEV.P",
        min_args: 1,
        max_args: None,
        eval: stdevp_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "VAR",
        min_args: 1,
        max_args: None,
        eval: var_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "VAR.S",
        min_args: 1,
        max_args: None,
        eval: var_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "VARP",
        min_args: 1,
        max_args: None,
        eval: varp_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "VAR.P",
        min_args: 1,
        max_args: None,
        eval: varp_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "MODE",
        min_args: 1,
        max_args: None,
        eval: mode_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "MODE.SNGL",
        min_args: 1,
        max_args: None,
        eval: mode_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "LARGE",
        min_args: 2,
        max_args: Some(2),
        eval: large_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "SMALL",
        min_args: 2,
        max_args: Some(2),
        eval: small_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "PERCENTILE",
        min_args: 2,
        max_args: Some(2),
        eval: percentile_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "PERCENTILE.INC",
        min_args: 2,
        max_args: Some(2),
        eval: percentile_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "QUARTILE",
        min_args: 2,
        max_args: Some(2),
        eval: quartile_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "QUARTILE.INC",
        min_args: 2,
        max_args: Some(2),
        eval: quartile_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "IFS",
        min_args: 2,
        max_args: None,
        eval: ifs_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "NOT",
        min_args: 1,
        max_args: Some(1),
        eval: not_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "IFNA",
        min_args: 2,
        max_args: Some(2),
        eval: ifna,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "SWITCH",
        min_args: 3,
        max_args: None,
        eval: switch_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "CONCAT",
        min_args: 1,
        max_args: None,
        eval: concat_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "TEXTJOIN",
        min_args: 3,
        max_args: None,
        eval: textjoin_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "LEFT",
        min_args: 1,
        max_args: Some(2),
        eval: left_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "RIGHT",
        min_args: 1,
        max_args: Some(2),
        eval: right_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "MID",
        min_args: 3,
        max_args: Some(3),
        eval: mid_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2],
    },
    FuncDef {
        name: "LEN",
        min_args: 1,
        max_args: Some(1),
        eval: len_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "FIND",
        min_args: 2,
        max_args: Some(3),
        eval: find_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2],
    },
    FuncDef {
        name: "SEARCH",
        min_args: 2,
        max_args: Some(3),
        eval: search_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2],
    },
    FuncDef {
        name: "SUBSTITUTE",
        min_args: 3,
        max_args: Some(4),
        eval: substitute_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2, 3],
    },
    FuncDef {
        name: "REPLACE",
        min_args: 4,
        max_args: Some(4),
        eval: replace_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2, 3],
    },
    FuncDef {
        name: "TRIM",
        min_args: 1,
        max_args: Some(1),
        eval: trim_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "UPPER",
        min_args: 1,
        max_args: Some(1),
        eval: upper_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "LOWER",
        min_args: 1,
        max_args: Some(1),
        eval: lower_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "TEXT",
        min_args: 2,
        max_args: Some(2),
        eval: text_fn,
        validate: Some(validate_text_format),
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "DATE",
        min_args: 3,
        max_args: Some(3),
        eval: date_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2],
    },
    FuncDef {
        name: "YEAR",
        min_args: 1,
        max_args: Some(1),
        eval: year_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "MONTH",
        min_args: 1,
        max_args: Some(1),
        eval: month_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "DAY",
        min_args: 1,
        max_args: Some(1),
        eval: day_fn,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "EDATE",
        min_args: 2,
        max_args: Some(2),
        eval: edate_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1],
    },
    FuncDef {
        name: "DATEDIF",
        min_args: 3,
        max_args: Some(3),
        eval: datedif_fn,
        validate: None,
        volatile: false,
        broadcast: &[0, 1, 2],
    },
    FuncDef {
        name: "TODAY",
        min_args: 0,
        max_args: Some(0),
        eval: today_fn,
        validate: None,
        volatile: true,
        broadcast: &[],
    },
    FuncDef {
        name: "NOW",
        min_args: 0,
        max_args: Some(0),
        eval: now_fn,
        validate: None,
        volatile: true,
        broadcast: &[],
    },
    FuncDef {
        name: "XLOOKUP",
        min_args: 3,
        max_args: Some(6),
        eval: xlookup,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "INDEX",
        min_args: 2,
        max_args: Some(3),
        eval: index_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "MATCH",
        min_args: 2,
        max_args: Some(3),
        eval: match_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "VLOOKUP",
        min_args: 3,
        max_args: Some(4),
        eval: vlookup,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "CHOOSE",
        min_args: 2,
        max_args: None,
        eval: choose,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "ROW",
        min_args: 0,
        max_args: Some(1),
        eval: row_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "COLUMN",
        min_args: 0,
        max_args: Some(1),
        eval: column_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "HLOOKUP",
        min_args: 3,
        max_args: Some(4),
        eval: hlookup,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "LOOKUP",
        min_args: 2,
        max_args: Some(3),
        eval: lookup_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "ROWS",
        min_args: 1,
        max_args: Some(1),
        eval: rows_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "COLUMNS",
        min_args: 1,
        max_args: Some(1),
        eval: columns_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "XMATCH",
        min_args: 2,
        max_args: Some(4),
        eval: xmatch,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "INDIRECT",
        min_args: 1,
        max_args: Some(2),
        eval: reserved_ref_eval,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "OFFSET",
        min_args: 3,
        max_args: Some(5),
        eval: reserved_ref_eval,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "ISBLANK",
        min_args: 1,
        max_args: Some(1),
        eval: isblank,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "ISNUMBER",
        min_args: 1,
        max_args: Some(1),
        eval: isnumber,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "ISTEXT",
        min_args: 1,
        max_args: Some(1),
        eval: istext,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "ISERROR",
        min_args: 1,
        max_args: Some(1),
        eval: iserror,
        validate: None,
        volatile: false,
        broadcast: &[0],
    },
    FuncDef {
        name: "NA",
        min_args: 0,
        max_args: Some(0),
        eval: na_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    // Deliberately NOT broadcast: an array HAS a type code (64), so this one answers about the container.
    FuncDef {
        name: "TYPE",
        min_args: 1,
        max_args: Some(1),
        eval: type_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "PMT",
        min_args: 3,
        max_args: Some(5),
        eval: pmt_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "FV",
        min_args: 3,
        max_args: Some(5),
        eval: fv_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "NPER",
        min_args: 3,
        max_args: Some(5),
        eval: nper_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "RATE",
        min_args: 3,
        max_args: Some(6),
        eval: rate_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "IPMT",
        min_args: 4,
        max_args: Some(6),
        eval: ipmt_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "PPMT",
        min_args: 4,
        max_args: Some(6),
        eval: ppmt_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "NPV",
        min_args: 2,
        max_args: None,
        eval: npv_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "IRR",
        min_args: 1,
        max_args: Some(2),
        eval: irr_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "XNPV",
        min_args: 3,
        max_args: Some(3),
        eval: xnpv_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
    FuncDef {
        name: "XIRR",
        min_args: 2,
        max_args: Some(3),
        eval: xirr_fn,
        validate: None,
        volatile: false,
        broadcast: &[],
    },
];
