// Concern: reads an xlsx package's non-visual facts: names, tables, numFmts, uncarried parts | Non-concern: appearance (xlsx_style.rs), cell values | IO: (path) -> XlsxMeta, numFmts, census, verdict

use std::collections::HashMap;
use std::fs::File;
use std::io::{BufReader, Read};
use std::path::Path;

use fsa1_model::{
    CUSTOM_NUMFMT_ID, CurrencySymbol, DatePattern, DateTimePattern, Format, TimePattern,
    effective_literal_format, is_display_exact,
};
use quick_xml::Reader;
use quick_xml::events::{BytesStart, Event};
use zip::ZipArchive;

use crate::error::{ErrorKind, IngestError};

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RawName {
    pub name: String,
    /// A 0-based index into the workbook's sheet order; `None` means workbook-scoped.
    pub local_sheet_id: Option<u32>,
    pub target: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RawTable {
    pub name: String,
    /// The table's full rectangle, header and totals rows included.
    pub ref_str: String,
    pub header_rows: u32,
    pub totals_rows: u32,
    pub columns: Vec<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct XlsxMeta {
    pub names: Vec<RawName>,
    pub tables: Vec<RawTable>,
}

/// A missing part yields no entries; a present but malformed one is a located refusal.
pub fn read_meta(path: &Path) -> Result<XlsxMeta, IngestError> {
    let file = File::open(path).map_err(|e| {
        IngestError::io(
            ErrorKind::SourceIo,
            format!("cannot open {:?} for metadata: {e}", path.display()),
        )
    })?;
    let mut zip = ZipArchive::new(BufReader::new(file)).map_err(|e| {
        IngestError::io(
            ErrorKind::SourceIo,
            format!("cannot read {:?} as a zip archive: {e}", path.display()),
        )
    })?;

    let names = match read_entry(&mut zip, "xl/workbook.xml")? {
        Some(xml) => parse_defined_names(&xml)?,
        None => Vec::new(),
    };

    // Collect the part names first (an immutable borrow), then read each (a mutable borrow).
    let table_parts: Vec<String> = zip
        .file_names()
        .filter(|n| n.starts_with("xl/tables/") && n.ends_with(".xml"))
        .map(str::to_string)
        .collect();
    let mut tables = Vec::with_capacity(table_parts.len());
    for part in table_parts {
        if let Some(xml) = read_entry(&mut zip, &part)?
            && let Some(t) = parse_table(&xml)?
        {
            tables.push(t);
        }
    }

    Ok(XlsxMeta { names, tables })
}

/// The SER3 role of a package part: `Allow` is carried on the round-trip, `Drop` is regenerated by the
/// reopening spreadsheet, `Refuse` is neither. The names in [`classify_part`] are today's instances of
/// each role, not the definition. This governs BOTH directions — the export writer emits the ALLOW set.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Disposition {
    Allow,
    Drop,
    Refuse,
}

/// A `*.rels` is structural glue every spreadsheet carries, so it is `Allow` under any folder; a
/// content part it points at is refused on its own name.
/// `xl/charts/chart1.xml` and no sibling of it. A chart's styling parts are Excel's own and this
/// import writes none of them back, so they stay REFUSED and keep being named.
pub(crate) fn is_chart_part(name: &str) -> bool {
    numbered(name, "xl/charts/chart")
}

fn is_drawing_part(name: &str) -> bool {
    numbered(name, "xl/drawings/drawing")
}

fn numbered(name: &str, prefix: &str) -> bool {
    name.strip_prefix(prefix)
        .and_then(|rest| rest.strip_suffix(".xml"))
        .is_some_and(|n| !n.is_empty() && n.bytes().all(|b| b.is_ascii_digit()))
}

fn classify_part(name: &str) -> Disposition {
    if name.ends_with('/') {
        return Disposition::Allow; // a zip directory entry, not a content part
    }
    if name == "[Content_Types].xml"
        || name.ends_with(".rels")
        || name == "xl/workbook.xml"
        || name == "xl/sharedStrings.xml"
        || name == "xl/styles.xml"
        || (name.starts_with("xl/worksheets/")
            && name.ends_with(".xml")
            && !name.contains("/_rels/"))
        || (name.starts_with("xl/theme/") && name.ends_with(".xml"))
        // ONLY the parts `pack` writes back: `xl/charts/` also holds Excel's `colors1.xml` and `style1.xml`, which nothing carries, and a part named by no warning is the silence SER3 bars.
        || is_chart_part(name)
        || is_drawing_part(name)
        || name == "docProps/core.xml"
        || name == "docProps/app.xml"
    {
        return Disposition::Allow;
    }
    if name == "xl/calcChain.xml"
        || name == "xl/metadata.xml"
        || name.starts_with("xl/printerSettings/")
    {
        return Disposition::Drop;
    }
    // The default is REFUSE, so an unrecognized part never passes silently.
    Disposition::Refuse
}

/// Runs before any read or write, so a refusal creates no output. Two triggers: a package part outside
/// ALLOW∪DROP, or a cell numFmt the content cannot carry — one outside the accepted catalog (on a
/// literal or a formula), or a value literal whose stored precision the display would not show.
pub fn strict_roundtrip_check(path: &Path) -> Result<(), IngestError> {
    let file = File::open(path).map_err(|e| {
        IngestError::io(
            ErrorKind::SourceIo,
            format!(
                "cannot open {:?} for the strict round-trip check: {e}",
                path.display()
            ),
        )
    })?;
    let mut zip = ZipArchive::new(BufReader::new(file)).map_err(|e| {
        IngestError::io(
            ErrorKind::SourceIo,
            format!("cannot read {:?} as a zip archive: {e}", path.display()),
        )
    })?;

    // Sorted, so a file with several out-of-scope parts always names the same one.
    let mut parts: Vec<String> = zip.file_names().map(str::to_string).collect();
    parts.sort();

    // Parts FIRST, so a part-bearing file is named as the offending part, not as one of its cells.
    for part in &parts {
        if classify_part(part) == Disposition::Refuse {
            return Err(IngestError::io(
                ErrorKind::Invalid,
                format!(
                    "cannot strictly round-trip {:?}: it carries the part {part:?}, which FSA1 neither models nor can regenerate (SER3) -- import without --strict to import its values lossily",
                    path.display()
                ),
            ));
        }
    }

    let styles = read_entry(&mut zip, "xl/styles.xml")?;
    let cell_xfs = match &styles {
        Some(xml) => parse_cell_xfs(xml)?,
        None => Vec::new(),
    };
    let num_fmts = match &styles {
        Some(xml) => parse_num_fmts(xml)?,
        None => HashMap::new(),
    };
    let sheet_name_by_part = sheet_name_by_part(&mut zip)?;
    let mut worksheet_parts: Vec<String> = parts
        .iter()
        .filter(|n| {
            n.starts_with("xl/worksheets/") && n.ends_with(".xml") && !n.contains("/_rels/")
        })
        .cloned()
        .collect();
    worksheet_parts.sort();
    for part in &worksheet_parts {
        let Some(xml) = read_entry(&mut zip, part)? else {
            continue;
        };
        let sheet = || {
            sheet_name_by_part
                .get(part)
                .cloned()
                .unwrap_or_else(|| part.clone())
        };
        for cell in scan_worksheet_cells(&xml, &cell_xfs)? {
            if cell.num_fmt_id == 0 {
                continue;
            }
            let code = num_fmts.get(&cell.num_fmt_id).map(String::as_str);
            match classify_numfmt(cell.num_fmt_id, code) {
                NumFmtClass::General => {}
                NumFmtClass::Accepted(format) => {
                    if cell.is_formula {
                        // A formula's value is computed at eval, never encoded in on-disk digits.
                        continue;
                    }
                    // A non-numeric literal carries no display precision to check.
                    let Some(value) = cell.value else { continue };
                    match effective_literal_format(format, value) {
                        None => {
                            return Err(IngestError::invalid_at_cell(
                                sheet(),
                                cell.cell_ref,
                                format!(
                                    "carries a negative accounting value under numFmtId {} ({}); a parenthesized accounting negative cannot be recovered from a value literal (§4.3) -- import without --strict to import its value lossily",
                                    cell.num_fmt_id,
                                    code.unwrap_or("built-in"),
                                ),
                            ));
                        }
                        Some(eff) if !is_display_exact(value, eff) => {
                            return Err(IngestError::invalid_at_cell(
                                sheet(),
                                cell.cell_ref,
                                format!(
                                    "carries a value with more precision than its number format (numFmtId {}, {}) displays; the displayed-form literal cannot encode it without falsifying the value or the format (§4.1) -- import without --strict to import its value lossily",
                                    cell.num_fmt_id,
                                    code.unwrap_or("built-in"),
                                ),
                            ));
                        }
                        Some(_) => {}
                    }
                }
                NumFmtClass::Exotic => {
                    return Err(IngestError::invalid_at_cell(
                        sheet(),
                        cell.cell_ref,
                        format!(
                            "carries a number format the skeleton does not model (numFmtId {}, {}) -- the exotic tail (conditional/mask/unknown) is not representable as typed content (GRID7); import without --strict to import its value lossily",
                            cell.num_fmt_id,
                            code.unwrap_or("built-in"),
                        ),
                    ));
                }
            }
        }
    }
    Ok(())
}

/// One workbook-wide thing an unpacked tree has no place for at all. These are absences, not
/// narrowings — no cell attribute stands in for any of them, so each is named once for the workbook
/// rather than per cell. DECLARATION order is report order, which the derived `Ord` is: a census is
/// sorted, never filtered against a second list a new variant could be left out of.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum UncarriedPart {
    ConditionalFormatting,
    RichTextRuns,
    FreezePanes,
    AutoFilter,
    TabColour,
    DataValidation,
    Hyperlinks,
    HiddenColumns,
    HiddenRows,
    /// A package part [`classify_part`] REFUSES, named by its own path. Read from the classifier
    /// rather than listed here, so a part newly classified is censused without touching this file.
    PackagePart(String),
}

impl UncarriedPart {
    /// The noun the SER3 line spells: `<part> not carried`. Exhaustive, so a new variant breaks the
    /// compile here rather than losing its line.
    pub fn spell(&self) -> String {
        match self {
            UncarriedPart::ConditionalFormatting => "conditional formatting".to_string(),
            UncarriedPart::RichTextRuns => "rich text runs".to_string(),
            UncarriedPart::FreezePanes => "freeze panes".to_string(),
            UncarriedPart::AutoFilter => "autofilter".to_string(),
            UncarriedPart::TabColour => "tab colour".to_string(),
            UncarriedPart::DataValidation => "data validation".to_string(),
            UncarriedPart::Hyperlinks => "hyperlinks".to_string(),
            UncarriedPart::HiddenColumns => "hidden columns".to_string(),
            UncarriedPart::HiddenRows => "hidden rows".to_string(),
            UncarriedPart::PackagePart(name) => name.clone(),
        }
    }
}

/// Both halves of one fact. A part `classify_part` REFUSES leaves whole and is named by its path — the
/// same classifier `--strict` refuses on, so the two cannot disagree about which parts cross. A part it
/// ALLOWS still states content FSA1 drops: `xl/worksheets/sheetN.xml` is allowed for its cells, and the
/// same part states the autofilter leaving with it. `Drop` is regenerated on reopen, so it is no loss.
pub fn uncarried_parts(path: &Path) -> Result<Vec<UncarriedPart>, IngestError> {
    let file = File::open(path).map_err(|e| {
        IngestError::io(
            ErrorKind::SourceIo,
            format!(
                "cannot open {:?} for the uncarried-part census: {e}",
                path.display()
            ),
        )
    })?;
    let mut zip = ZipArchive::new(BufReader::new(file)).map_err(|e| {
        IngestError::io(
            ErrorKind::SourceIo,
            format!("cannot read {:?} as a zip archive: {e}", path.display()),
        )
    })?;

    let mut found: Vec<UncarriedPart> = zip
        .file_names()
        .filter(|name| classify_part(name) == Disposition::Refuse)
        .map(|name| UncarriedPart::PackagePart(name.to_string()))
        .collect();
    if let Some(xml) = read_entry(&mut zip, "xl/sharedStrings.xml")?
        && shared_strings_carry_runs(&xml)?
    {
        found.push(UncarriedPart::RichTextRuns);
    }
    let mut worksheet_parts: Vec<String> = zip
        .file_names()
        .filter(|n| {
            n.starts_with("xl/worksheets/") && n.ends_with(".xml") && !n.contains("/_rels/")
        })
        .map(str::to_string)
        .collect();
    worksheet_parts.sort();
    for part in &worksheet_parts {
        if let Some(xml) = read_entry(&mut zip, part)? {
            found.extend(worksheet_features(&xml)?);
        }
    }
    found.sort();
    found.dedup();
    Ok(found)
}

/// A `<si>` holding `<r>` runs is one string in several looks, and the grid cell it becomes holds one.
/// The LOOK is the loss, so what counts is an `<rPr>`: a writer that splits a plain string into runs
/// stating no formatting (`<si><r><t>plain</t></r></si>`) loses nothing, and may not be reported as if
/// it did.
fn shared_strings_carry_runs(xml: &str) -> Result<bool, IngestError> {
    let mut reader = Reader::from_str(xml);
    loop {
        match reader.read_event().map_err(xml_err)? {
            Event::Start(e) | Event::Empty(e) if e.local_name().as_ref() == b"rPr" => {
                return Ok(true);
            }
            Event::Eof => return Ok(false),
            _ => {}
        }
    }
}

/// A `<pane>` with no frozen state is a split view, which is a viewport and not a document fact; a
/// `<col hidden>` and a `<row hidden>` are read off the very elements the width and the height come
/// from.
fn worksheet_features(xml: &str) -> Result<Vec<UncarriedPart>, IngestError> {
    let mut reader = Reader::from_str(xml);
    let mut out = Vec::new();
    loop {
        let e = match reader.read_event().map_err(xml_err)? {
            Event::Start(e) | Event::Empty(e) => e,
            Event::Eof => break,
            _ => continue,
        };
        let hidden = || attr(&e, b"hidden").is_some_and(|v| v != "0" && v != "false");
        let feature = match e.local_name().as_ref() {
            b"conditionalFormatting" => Some(UncarriedPart::ConditionalFormatting),
            b"autoFilter" => Some(UncarriedPart::AutoFilter),
            b"dataValidation" => Some(UncarriedPart::DataValidation),
            b"hyperlink" => Some(UncarriedPart::Hyperlinks),
            b"tabColor" => Some(UncarriedPart::TabColour),
            b"pane" if attr(&e, b"state").is_some_and(|s| s.starts_with("frozen")) => {
                Some(UncarriedPart::FreezePanes)
            }
            b"col" if hidden() => Some(UncarriedPart::HiddenColumns),
            b"row" if hidden() => Some(UncarriedPart::HiddenRows),
            _ => None,
        };
        if let Some(feature) = feature
            && !out.contains(&feature)
        {
            out.push(feature);
        }
    }
    Ok(out)
}

/// `sheet name -> (A1 cell ref -> Format)`. Only cells whose numFmt classifies as accepted appear.
pub type NumFmtMap = HashMap<String, HashMap<String, Format>>;

/// `format_code` is present only for a custom id (164 or above); a built-in carries `None`.
pub struct CoercedCell {
    pub sheet: String,
    pub cell: String,
    pub num_fmt_id: u32,
    pub format_code: Option<String>,
}

/// Every non-General cell, because a LOSSY import drops all of them: it reads calamine's cached values
/// and never `xl/styles.xml`, so it cannot report the coercion itself. Deterministic order: worksheet
/// parts sorted, cells in document order.
pub fn numfmt_coercions(path: &Path) -> Result<Vec<CoercedCell>, IngestError> {
    let file = File::open(path).map_err(|e| {
        IngestError::io(
            ErrorKind::SourceIo,
            format!(
                "cannot open {:?} for numFmt coercion enumeration: {e}",
                path.display()
            ),
        )
    })?;
    let mut zip = ZipArchive::new(BufReader::new(file)).map_err(|e| {
        IngestError::io(
            ErrorKind::SourceIo,
            format!("cannot read {:?} as a zip archive: {e}", path.display()),
        )
    })?;
    let styles = read_entry(&mut zip, "xl/styles.xml")?;
    let cell_xfs = match &styles {
        Some(xml) => parse_cell_xfs(xml)?,
        None => Vec::new(),
    };
    let num_fmts = match &styles {
        Some(xml) => parse_num_fmts(xml)?,
        None => HashMap::new(),
    };
    let sheet_name_by_part = sheet_name_by_part(&mut zip)?;
    let mut worksheet_parts: Vec<String> = zip
        .file_names()
        .filter(|n| {
            n.starts_with("xl/worksheets/") && n.ends_with(".xml") && !n.contains("/_rels/")
        })
        .map(str::to_string)
        .collect();
    worksheet_parts.sort();
    let mut out = Vec::new();
    for part in &worksheet_parts {
        let Some(xml) = read_entry(&mut zip, part)? else {
            continue;
        };
        let sheet = sheet_name_by_part
            .get(part)
            .cloned()
            .unwrap_or_else(|| part.clone());
        for cell in scan_worksheet_cells(&xml, &cell_xfs)? {
            if cell.num_fmt_id == 0 {
                continue;
            }
            out.push(CoercedCell {
                sheet: sheet.clone(),
                cell: cell.cell_ref,
                num_fmt_id: cell.num_fmt_id,
                format_code: num_fmts.get(&cell.num_fmt_id).cloned(),
            });
        }
    }
    Ok(out)
}

/// The stored `Format` is the RAW classification — an `Accounting` stays `Accounting`, because this map
/// is numFmt-only and cannot know a cell's value kind; the reader applies the value-aware remap.
pub fn numfmt_map(path: &Path) -> Result<NumFmtMap, IngestError> {
    let file = File::open(path).map_err(|e| {
        IngestError::io(
            ErrorKind::SourceIo,
            format!(
                "cannot open {:?} for numFmt classification: {e}",
                path.display()
            ),
        )
    })?;
    let mut zip = ZipArchive::new(BufReader::new(file)).map_err(|e| {
        IngestError::io(
            ErrorKind::SourceIo,
            format!("cannot read {:?} as a zip archive: {e}", path.display()),
        )
    })?;
    let styles = read_entry(&mut zip, "xl/styles.xml")?;
    let cell_xfs = match &styles {
        Some(xml) => parse_cell_xfs(xml)?,
        None => Vec::new(),
    };
    let num_fmts = match &styles {
        Some(xml) => parse_num_fmts(xml)?,
        None => HashMap::new(),
    };
    let sheet_name_by_part = sheet_name_by_part(&mut zip)?;
    let mut worksheet_parts: Vec<String> = zip
        .file_names()
        .filter(|n| {
            n.starts_with("xl/worksheets/") && n.ends_with(".xml") && !n.contains("/_rels/")
        })
        .map(str::to_string)
        .collect();
    worksheet_parts.sort();
    let mut out: NumFmtMap = HashMap::new();
    for part in &worksheet_parts {
        let Some(xml) = read_entry(&mut zip, part)? else {
            continue;
        };
        let mut sheet_map: HashMap<String, Format> = HashMap::new();
        for cell in scan_worksheet_cells(&xml, &cell_xfs)? {
            if cell.num_fmt_id == 0 {
                continue;
            }
            let code = num_fmts.get(&cell.num_fmt_id).map(String::as_str);
            if let NumFmtClass::Accepted(format) = classify_numfmt(cell.num_fmt_id, code) {
                sheet_map.insert(cell.cell_ref, format);
            }
        }
        if !sheet_map.is_empty() {
            let sheet = sheet_name_by_part
                .get(part)
                .cloned()
                .unwrap_or_else(|| part.clone());
            out.insert(sheet, sheet_map);
        }
    }
    Ok(out)
}

/// `Exotic` is the conditional/mask/unknown/unmodeled tail — a located refusal under `--strict`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum NumFmtClass {
    General,
    Accepted(Format),
    Exotic,
}

/// A custom id (>= [`CUSTOM_NUMFMT_ID`]) resolves through its `formatCode`, so an absent code is exotic.
fn classify_numfmt(id: u32, custom_code: Option<&str>) -> NumFmtClass {
    if id == 0 {
        return NumFmtClass::General;
    }
    if let Some(format) = builtin_format(id) {
        return NumFmtClass::Accepted(format);
    }
    if id < CUSTOM_NUMFMT_ID {
        return NumFmtClass::Exotic;
    }
    match custom_code.and_then(classify_custom_code) {
        Some(format) => NumFmtClass::Accepted(format),
        None => NumFmtClass::Exotic,
    }
}

/// The ECMA-376 built-in ids (0-163) the catalog models; a built-in outside this table is exotic.
fn builtin_format(id: u32) -> Option<Format> {
    Some(match id {
        1 => Format::Fixed { decimals: 0 },
        2 => Format::Fixed { decimals: 2 },
        3 => Format::Grouped { decimals: 0 },
        4 => Format::Grouped { decimals: 2 },
        5 | 6 | 42 => Format::Accounting {
            symbol: CurrencySymbol::Dollar,
            decimals: 0,
        },
        7 | 8 | 44 => Format::Accounting {
            symbol: CurrencySymbol::Dollar,
            decimals: 2,
        },
        9 => Format::Percent { decimals: 0 },
        10 => Format::Percent { decimals: 2 },
        14 => Format::Date(DatePattern::MmDdYy),
        15 => Format::Date(DatePattern::DMmmYy),
        17 => Format::Date(DatePattern::MmmYy),
        18 => Format::Time(TimePattern::Hm12),
        20 => Format::Time(TimePattern::Hm),
        21 => Format::Time(TimePattern::Hms),
        22 => Format::DateTime(DateTimePattern::MdyHm),
        _ => return None,
    })
}

fn classify_custom_code(code: &str) -> Option<Format> {
    Format::from_code(&preprocess_format_code(code)?)
}

/// A COLOR bracket is dropped as a cosmetic loss; a `[$sym-loc]` contributes its glyph; a CONDITIONAL
/// bracket is value-dependent, which the content cannot carry, so it is exotic — as is an unbalanced `[`.
fn preprocess_format_code(code: &str) -> Option<String> {
    let mut out = String::with_capacity(code.len());
    let mut rest = code;
    while let Some(open) = rest.find('[') {
        out.push_str(&rest[..open]);
        let close = open + rest[open..].find(']')?;
        let inner = &rest[open + 1..close];
        if let Some(sym) = inner.strip_prefix('$') {
            out.push_str(sym.split('-').next().unwrap_or(""));
        } else if is_color_bracket(inner) {
        } else {
            return None;
        }
        rest = &rest[close + 1..];
    }
    out.push_str(rest);
    Some(out)
}

fn is_color_bracket(inner: &str) -> bool {
    let lower = inner.to_ascii_lowercase();
    matches!(
        lower.as_str(),
        "black" | "blue" | "cyan" | "green" | "magenta" | "red" | "white" | "yellow"
    ) || lower.starts_with("color ")
}

/// Only the CUSTOM ids appear here; a built-in resolves through [`builtin_format`] instead.
fn parse_num_fmts(xml: &str) -> Result<HashMap<u32, String>, IngestError> {
    let mut reader = Reader::from_str(xml);
    let mut out = HashMap::new();
    loop {
        match reader.read_event().map_err(xml_err)? {
            Event::Start(e) | Event::Empty(e) if e.local_name().as_ref() == b"numFmt" => {
                if let (Some(id), Some(code)) = (
                    attr(&e, b"numFmtId").and_then(|s| s.parse::<u32>().ok()),
                    attr(&e, b"formatCode"),
                ) {
                    out.insert(id, code);
                }
            }
            Event::Eof => break,
            _ => {}
        }
    }
    Ok(out)
}

struct RawCell {
    cell_ref: String,
    num_fmt_id: u32,
    is_formula: bool,
    value: Option<f64>,
}

/// Document order is preserved, so the strict pre-flight names a deterministic first offender.
fn scan_worksheet_cells(xml: &str, cell_xfs: &[u32]) -> Result<Vec<RawCell>, IngestError> {
    let mut reader = Reader::from_str(xml);
    let mut out = Vec::new();
    loop {
        match reader.read_event().map_err(xml_err)? {
            Event::Empty(e) if e.local_name().as_ref() == b"c" => {
                let (cell_ref, num_fmt_id) = cell_head(&e, cell_xfs);
                out.push(RawCell {
                    cell_ref,
                    num_fmt_id,
                    is_formula: false,
                    value: None,
                });
            }
            Event::Start(e) if e.local_name().as_ref() == b"c" => {
                let (cell_ref, num_fmt_id) = cell_head(&e, cell_xfs);
                let mut is_formula = false;
                let mut value = None;
                let mut in_v = false;
                loop {
                    match reader.read_event().map_err(xml_err)? {
                        Event::Start(x) | Event::Empty(x) if x.local_name().as_ref() == b"f" => {
                            is_formula = true;
                        }
                        Event::Start(x) if x.local_name().as_ref() == b"v" => in_v = true,
                        Event::End(x) if x.local_name().as_ref() == b"v" => in_v = false,
                        Event::Text(t) if in_v => {
                            value = decode_text(&t)?.trim().parse::<f64>().ok();
                        }
                        Event::End(x) if x.local_name().as_ref() == b"c" => break,
                        Event::Eof => break,
                        _ => {}
                    }
                }
                out.push(RawCell {
                    cell_ref,
                    num_fmt_id,
                    is_formula,
                    value,
                });
            }
            Event::Eof => break,
            _ => {}
        }
    }
    Ok(out)
}

fn cell_head(e: &BytesStart, cell_xfs: &[u32]) -> (String, u32) {
    let cell_ref = attr(e, b"r").unwrap_or_default();
    let s = attr(e, b"s")
        .and_then(|v| v.parse::<usize>().ok())
        .unwrap_or(0);
    let num_fmt_id = cell_xfs.get(s).copied().unwrap_or(0);
    (cell_ref, num_fmt_id)
}

/// A cell's `s` indexes `cellXfs`, NOT the `cellStyleXfs` block that precedes it and also carries `<xf>`.
fn parse_cell_xfs(xml: &str) -> Result<Vec<u32>, IngestError> {
    let mut reader = Reader::from_str(xml);
    let mut out = Vec::new();
    let mut in_cell_xfs = false;
    loop {
        match reader.read_event().map_err(xml_err)? {
            Event::Start(e) if e.local_name().as_ref() == b"cellXfs" => in_cell_xfs = true,
            Event::End(e) if e.local_name().as_ref() == b"cellXfs" => in_cell_xfs = false,
            Event::Start(e) | Event::Empty(e)
                if in_cell_xfs && e.local_name().as_ref() == b"xf" =>
            {
                let id = attr(&e, b"numFmtId")
                    .and_then(|s| s.parse::<u32>().ok())
                    .unwrap_or(0);
                out.push(id);
            }
            Event::Eof => break,
            _ => {}
        }
    }
    Ok(out)
}

/// A part with no resolvable name is absent, and the caller falls back to the part path.
pub(crate) fn sheet_name_by_part(
    zip: &mut ZipArchive<BufReader<File>>,
) -> Result<HashMap<String, String>, IngestError> {
    let Some(workbook) = read_entry(zip, "xl/workbook.xml")? else {
        return Ok(HashMap::new());
    };
    let sheets = parse_workbook_sheets(&workbook)?;
    let targets = read_rels(zip, "xl/workbook.xml")?;
    let mut out = HashMap::new();
    for (name, rid) in sheets {
        if let Some(part) = targets.get(&rid) {
            out.insert(part.clone(), name);
        }
    }
    Ok(out)
}

fn parse_workbook_sheets(xml: &str) -> Result<Vec<(String, String)>, IngestError> {
    let mut reader = Reader::from_str(xml);
    let mut out = Vec::new();
    loop {
        match reader.read_event().map_err(xml_err)? {
            Event::Start(e) | Event::Empty(e) if e.local_name().as_ref() == b"sheet" => {
                let name = attr(&e, b"name").unwrap_or_default();
                let rid = attr(&e, b"r:id")
                    .or_else(|| attr(&e, b"id"))
                    .unwrap_or_default();
                if !name.is_empty() && !rid.is_empty() {
                    out.push((name, rid));
                }
            }
            Event::Eof => break,
            _ => {}
        }
    }
    Ok(out)
}

/// The relationships a part declares, `Id -> the package path the `Target` resolves to`. A part's
/// rels live at `<dir>/_rels/<file>.rels` and its relative targets join onto `<dir>`, so the OWNING
/// part is what this takes: the one rels reader in the crate cannot then be pointed at a base its
/// targets do not belong to. A part declaring none has no rels file and yields an empty map.
pub(crate) fn read_rels(
    zip: &mut ZipArchive<BufReader<File>>,
    part: &str,
) -> Result<HashMap<String, String>, IngestError> {
    let (dir, file) = part.rsplit_once('/').unwrap_or(("", part));
    let xml = read_entry(zip, &format!("{dir}/_rels/{file}.rels"))?.unwrap_or_default();
    let mut reader = Reader::from_str(&xml);
    let mut out = HashMap::new();
    loop {
        match reader.read_event().map_err(xml_err)? {
            Event::Start(e) | Event::Empty(e) if e.local_name().as_ref() == b"Relationship" => {
                let id = attr(&e, b"Id").unwrap_or_default();
                let target = attr(&e, b"Target").unwrap_or_default();
                if !id.is_empty() && !target.is_empty() {
                    out.insert(id, resolve_target(dir, &target));
                }
            }
            Event::Eof => break,
            _ => {}
        }
    }
    Ok(out)
}

/// A `Target` is package-absolute when it leads with `/` and relative to the owning part's directory
/// otherwise. Both spellings are in the wild for one relationship — openpyxl writes
/// `/xl/drawings/drawing1.xml` where Excel writes `../drawings/drawing1.xml` — so both resolve here.
pub(crate) fn resolve_target(dir: &str, target: &str) -> String {
    if let Some(abs) = target.strip_prefix('/') {
        return abs.to_string();
    }
    let mut parts: Vec<&str> = dir.split('/').filter(|s| !s.is_empty()).collect();
    for segment in target.split('/') {
        match segment {
            "" | "." => {}
            ".." => {
                parts.pop();
            }
            other => parts.push(other),
        }
    }
    parts.join("/")
}

pub(crate) fn read_entry(
    zip: &mut ZipArchive<BufReader<File>>,
    name: &str,
) -> Result<Option<String>, IngestError> {
    let mut entry = match zip.by_name(name) {
        Ok(e) => e,
        Err(zip::result::ZipError::FileNotFound) => return Ok(None),
        Err(e) => {
            return Err(IngestError::io(
                ErrorKind::SourceIo,
                format!("cannot read zip entry {name:?}: {e}"),
            ));
        }
    };
    let mut buf = String::new();
    entry.read_to_string(&mut buf).map_err(|e| {
        IngestError::io(
            ErrorKind::SourceIo,
            format!("cannot decode zip entry {name:?}: {e}"),
        )
    })?;
    Ok(Some(buf))
}

fn parse_defined_names(xml: &str) -> Result<Vec<RawName>, IngestError> {
    let mut reader = Reader::from_str(xml);
    let mut out = Vec::new();
    loop {
        match reader.read_event().map_err(xml_err)? {
            Event::Start(e) if e.local_name().as_ref() == b"definedName" => {
                let name = attr(&e, b"name").unwrap_or_default();
                let local_sheet_id = attr(&e, b"localSheetId").and_then(|s| s.parse::<u32>().ok());
                let mut target = String::new();
                loop {
                    match reader.read_event().map_err(xml_err)? {
                        Event::Text(t) => target.push_str(&decode_text(&t)?),
                        // A predefined entity is its OWN event, never text; skipping it drops the char.
                        Event::GeneralRef(r) => {
                            let decoded = match r.resolve_char_ref().map_err(xml_err)? {
                                Some(ch) => ch.to_string(),
                                None => match r.decode().unwrap_or_default().as_ref() {
                                    "lt" => "<".to_string(),
                                    "gt" => ">".to_string(),
                                    "amp" => "&".to_string(),
                                    "quot" => "\"".to_string(),
                                    "apos" => "'".to_string(),
                                    other => {
                                        return Err(IngestError::io(
                                            ErrorKind::Invalid,
                                            format!(
                                                "defined name {name:?} references the unknown XML entity &{};",
                                                other
                                            ),
                                        ));
                                    }
                                },
                            };
                            target.push_str(&decoded);
                        }
                        Event::End(end) if end.local_name().as_ref() == b"definedName" => break,
                        Event::Eof => break,
                        _ => {}
                    }
                }
                if !name.is_empty() {
                    out.push(RawName {
                        name,
                        local_sheet_id,
                        target,
                    });
                }
            }
            Event::Eof => break,
            _ => {}
        }
    }
    Ok(out)
}

/// `None` when the part carries no usable `ref`.
fn parse_table(xml: &str) -> Result<Option<RawTable>, IngestError> {
    let mut reader = Reader::from_str(xml);
    let mut name = String::new();
    let mut ref_str = String::new();
    let mut header_rows = 1u32; // Excel's default when the attribute is absent
    let mut totals_rows = 0u32;
    let mut columns = Vec::new();
    loop {
        let ev = reader.read_event().map_err(xml_err)?;
        match ev {
            Event::Start(e) | Event::Empty(e) if e.local_name().as_ref() == b"table" => {
                // displayName is the spelling a formula references the table by.
                name = attr(&e, b"displayName")
                    .or_else(|| attr(&e, b"name"))
                    .unwrap_or_default();
                ref_str = attr(&e, b"ref").unwrap_or_default();
                if let Some(h) = attr(&e, b"headerRowCount").and_then(|s| s.parse().ok()) {
                    header_rows = h;
                }
                if let Some(t) = attr(&e, b"totalsRowCount").and_then(|s| s.parse().ok()) {
                    totals_rows = t;
                }
            }
            Event::Start(e) | Event::Empty(e) if e.local_name().as_ref() == b"tableColumn" => {
                if let Some(c) = attr(&e, b"name") {
                    columns.push(c);
                }
            }
            Event::Eof => break,
            _ => {}
        }
    }
    if name.is_empty() || ref_str.is_empty() {
        return Ok(None);
    }
    Ok(Some(RawTable {
        name,
        ref_str,
        header_rows,
        totals_rows,
        columns,
    }))
}

/// The XML is read from a `&str`, so attribute bytes are valid UTF-8 and only unescaping remains.
pub(crate) fn attr(e: &BytesStart, key: &[u8]) -> Option<String> {
    for a in e.attributes().flatten() {
        if a.key.as_ref() == key {
            let raw = std::str::from_utf8(a.value.as_ref()).ok()?;
            return quick_xml::escape::unescape(raw)
                .ok()
                .map(|c| c.into_owned());
        }
    }
    None
}

pub(crate) fn decode_text(t: &quick_xml::events::BytesText<'_>) -> Result<String, IngestError> {
    let raw = t.decode().map_err(|e| {
        IngestError::io(ErrorKind::SourceIo, format!("cannot decode xml text: {e}"))
    })?;
    quick_xml::escape::unescape(&raw)
        .map(|c| c.into_owned())
        .map_err(|e| IngestError::io(ErrorKind::SourceIo, format!("bad xml entity: {e}")))
}

pub(crate) fn xml_err(e: quick_xml::Error) -> IngestError {
    IngestError::io(ErrorKind::SourceIo, format!("malformed xml metadata: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_scoped_and_global_defined_names() {
        let xml = r#"<workbook><definedNames>
            <definedName name="TaxRate">Data!$H$1</definedName>
            <definedName name="Local" localSheetId="2">Sheet3!$A$1</definedName>
            <definedName name="Arr">{1,2,3}</definedName>
            </definedNames></workbook>"#;
        let names = parse_defined_names(xml).unwrap();
        assert_eq!(names.len(), 3);
        assert_eq!(
            names[0],
            RawName {
                name: "TaxRate".into(),
                local_sheet_id: None,
                target: "Data!$H$1".into()
            }
        );
        assert_eq!(names[1].local_sheet_id, Some(2));
        assert_eq!(names[2].target, "{1,2,3}");
    }

    #[test]
    fn parses_a_table_part_with_defaults_and_explicit_counts() {
        let t1 = parse_table(
            r#"<table displayName="Table13" ref="A1:B89" totalsRowShown="0">
                <tableColumns count="2"><tableColumn id="1" name="Date"/>
                <tableColumn id="3" name="Amount"/></tableColumns></table>"#,
        )
        .unwrap()
        .unwrap();
        assert_eq!(t1.name, "Table13");
        assert_eq!(t1.ref_str, "A1:B89");
        assert_eq!(t1.header_rows, 1, "no headerRowCount attr, so the default");
        assert_eq!(t1.totals_rows, 0, "no totalsRowCount attr, so the default");
        assert_eq!(t1.columns, vec!["Date", "Amount"]);

        let t2 = parse_table(
            r#"<table displayName="T" ref="A1:C5" headerRowCount="1" totalsRowCount="1">
                <tableColumns><tableColumn name="R"/><tableColumn name="Q1"/>
                <tableColumn name="Q2"/></tableColumns></table>"#,
        )
        .unwrap()
        .unwrap();
        assert_eq!(t2.totals_rows, 1);
        assert_eq!(t2.columns, vec!["R", "Q1", "Q2"]);
    }

    #[test]
    fn a_table_without_a_ref_is_skipped() {
        assert_eq!(parse_table("<table displayName=\"X\"/>").unwrap(), None);
    }

    #[test]
    fn classify_part_sorts_parts_into_the_ser3_roles() {
        for p in [
            "[Content_Types].xml",
            "_rels/.rels",
            "xl/_rels/workbook.xml.rels",
            "xl/worksheets/_rels/sheet1.xml.rels",
            "xl/workbook.xml",
            "xl/worksheets/sheet1.xml",
            "xl/sharedStrings.xml",
            "xl/styles.xml",
            "xl/theme/theme1.xml",
            "docProps/core.xml",
            "docProps/app.xml",
            "xl/",
            "xl/charts/chart1.xml",
            "xl/drawings/drawing1.xml",
        ] {
            assert_eq!(classify_part(p), Disposition::Allow, "{p} should be ALLOW");
        }
        for p in [
            "xl/calcChain.xml",
            "xl/metadata.xml",
            "xl/printerSettings/printerSettings1.bin",
        ] {
            assert_eq!(classify_part(p), Disposition::Drop, "{p} should be DROP");
        }
        // The tail, plus an unrecognized part, which must never pass silently.
        for p in [
            "xl/tables/table1.xml",
            "xl/pivotTables/pivotTable1.xml",
            "xl/media/image1.png",
            "xl/vbaProject.bin",
            "customXml/item1.xml",
            "docProps/custom.xml",
            "xl/whatever_new_part.xml",
        ] {
            assert_eq!(
                classify_part(p),
                Disposition::Refuse,
                "{p} should be REFUSE"
            );
        }
    }

    /// The minimal package plus `extra`, each written with a placeholder body: the census classifies a
    /// part by NAME, so its content is not what is under test.
    fn package_with_parts(extra: &[&str]) -> std::path::PathBuf {
        use std::io::Write;
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let path = std::env::temp_dir().join(format!(
            "fsa1-xlsx-census-{}-{nanos}.xlsx",
            std::process::id()
        ));
        let f = File::create(&path).unwrap();
        let mut zw = zip::ZipWriter::new(f);
        let opts: zip::write::FileOptions<'_, ()> = zip::write::FileOptions::default();
        let base: [(&str, &str); 6] = [
            ("[Content_Types].xml", "<Types/>"),
            ("_rels/.rels", "<Relationships/>"),
            (
                "xl/workbook.xml",
                r#"<workbook><sheets><sheet name="S" sheetId="1" r:id="rId1"/></sheets></workbook>"#,
            ),
            (
                "xl/_rels/workbook.xml.rels",
                r#"<Relationships><Relationship Id="rId1" Target="worksheets/sheet1.xml"/></Relationships>"#,
            ),
            (
                "xl/styles.xml",
                "<styleSheet><cellXfs><xf numFmtId=\"0\"/></cellXfs></styleSheet>",
            ),
            (
                "xl/worksheets/sheet1.xml",
                "<worksheet><sheetData/></worksheet>",
            ),
        ];
        for (name, body) in base
            .iter()
            .map(|(n, b)| (*n, *b))
            .chain(extra.iter().map(|name| (*name, "<placeholder/>")))
        {
            zw.start_file(name, opts).unwrap();
            zw.write_all(body.as_bytes()).unwrap();
        }
        zw.finish().unwrap();
        path
    }

    /// The census and the `--strict` pre-flight read ONE classifier, and this asserts that agreement
    /// rather than a second hand-written list: reclassify a name, or hand a package a part nobody
    /// anticipated, and the census follows with no edit here. A hand list is precisely what let a chart
    /// part cross in silence under `nothing lost` while `--strict` refused the same file for it.
    #[test]
    fn the_census_names_exactly_the_package_parts_the_classifier_refuses() {
        let path = package_with_parts(&[
            "xl/charts/chart1.xml",
            "xl/drawings/drawing1.xml",
            "xl/chartsheets/sheet1.xml",
            "xl/comments/comment1.xml",
            "xl/media/image1.png",
            "xl/pivotTables/pivotTable1.xml",
            "xl/vbaProject.bin",
            "xl/externalLinks/externalLink1.xml",
            "xl/a_part_no_one_has_classified_yet.xml",
            "xl/calcChain.xml",
            "xl/theme/theme1.xml",
        ]);
        let censused: Vec<String> = uncarried_parts(&path)
            .unwrap()
            .iter()
            .filter_map(|p| match p {
                UncarriedPart::PackagePart(name) => Some(name.clone()),
                _ => None,
            })
            .collect();

        let file = File::open(&path).unwrap();
        let zip = ZipArchive::new(BufReader::new(file)).unwrap();
        let mut refused: Vec<String> = zip
            .file_names()
            .filter(|n| classify_part(n) == Disposition::Refuse)
            .map(str::to_string)
            .collect();
        refused.sort();
        assert_eq!(
            censused, refused,
            "the census must be the classifier's REFUSE set, not a list beside it"
        );
        assert!(censused.iter().any(|n| n == "xl/chartsheets/sheet1.xml"));
        assert!(
            !censused.iter().any(|n| n == "xl/calcChain.xml"),
            "a DROP part is regenerated by the reopening spreadsheet, so it is no loss"
        );
        assert!(!censused.iter().any(|n| n == "xl/theme/theme1.xml"));

        // `pack` writes a chart and its drawing back, so neither is censused as not carried.
        assert!(!censused.iter().any(|n| n == "xl/charts/chart1.xml"));
        assert!(!censused.iter().any(|n| n == "xl/drawings/drawing1.xml"));
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn a_shared_string_split_into_unformatted_runs_carries_no_look_to_lose() {
        assert!(
            !shared_strings_carry_runs("<sst><si><r><t>plain</t></r></si></sst>").unwrap(),
            "one look spelled as a run is the same one look"
        );
        assert!(
            !shared_strings_carry_runs("<sst><si><r><t>two</t></r><r><t> runs</t></r></si></sst>")
                .unwrap(),
            "several runs, none stating any formatting, still make one look"
        );
        assert!(
            shared_strings_carry_runs(
                "<sst><si><r><rPr><b/></rPr><t>Ada</t></r><r><t> Lovelace</t></r></si></sst>"
            )
            .unwrap(),
            "an rPr is the second look, and the grid cell holds one"
        );
    }

    #[test]
    fn parse_cell_xfs_reads_cellxfs_only_not_cellstylexfs() {
        let xml = r#"<styleSheet><numFmts count="1"><numFmt numFmtId="164" formatCode="yyyy-mm-dd"/></numFmts>
            <cellStyleXfs count="1"><xf numFmtId="0"/></cellStyleXfs>
            <cellXfs count="2"><xf numFmtId="0" xfId="0"/><xf numFmtId="164" xfId="0"/></cellXfs></styleSheet>"#;
        assert_eq!(
            parse_cell_xfs(xml).unwrap(),
            vec![0, 164],
            "the cellStyleXfs <xf> must not enter the index"
        );
    }

    #[test]
    fn scan_worksheet_cells_reads_ref_numfmt_formula_flag_and_value() {
        let cell_xfs = vec![0u32, 164u32];
        // A2: General value; D2 s=1 -> numFmtId 164, a value; B1 s=1 -> a formula.
        let xml = r#"<worksheet><sheetData><row r="2">
            <c r="A2" t="n"><v>1</v></c><c r="D2" s="1" t="n"><v>45306</v></c></row>
            <row r="1"><c r="B1" s="1"><f>A1*2</f><v>20</v></c></row></sheetData></worksheet>"#;
        let cells = scan_worksheet_cells(xml, &cell_xfs).unwrap();
        let by_ref = |r: &str| cells.iter().find(|c| c.cell_ref == r).unwrap();
        assert_eq!(by_ref("A2").num_fmt_id, 0);
        assert!(!by_ref("A2").is_formula);
        assert_eq!(by_ref("A2").value, Some(1.0));
        assert_eq!(by_ref("D2").num_fmt_id, 164);
        assert!(!by_ref("D2").is_formula);
        assert_eq!(by_ref("D2").value, Some(45306.0));
        assert_eq!(by_ref("B1").num_fmt_id, 164);
        assert!(by_ref("B1").is_formula);
    }

    #[test]
    fn classify_numfmt_sorts_builtins_customs_and_the_exotic_tail() {
        assert_eq!(classify_numfmt(0, None), NumFmtClass::General);
        assert_eq!(
            classify_numfmt(10, None),
            NumFmtClass::Accepted(Format::Percent { decimals: 2 }),
            "a built-in needs no formatCode"
        );
        assert_eq!(
            classify_numfmt(14, None),
            NumFmtClass::Accepted(Format::Date(DatePattern::MmDdYy))
        );
        assert_eq!(
            classify_numfmt(44, None),
            NumFmtClass::Accepted(Format::Accounting {
                symbol: CurrencySymbol::Dollar,
                decimals: 2
            })
        );
        assert_eq!(
            classify_numfmt(19, None),
            NumFmtClass::Exotic,
            "19 is `h:mm:ss AM/PM`, an unmodeled built-in"
        );
        assert_eq!(
            classify_numfmt(49, Some("@")),
            NumFmtClass::Exotic,
            "49 is the `@` text built-in"
        );
        assert_eq!(
            classify_numfmt(164, Some("0.00%")),
            NumFmtClass::Accepted(Format::Percent { decimals: 2 })
        );
        assert_eq!(
            classify_numfmt(165, Some("[Blue]m/d/yyyy")),
            NumFmtClass::Accepted(Format::Date(DatePattern::Mdy)),
            "a color bracket is dropped and the underlying format recovered"
        );
        assert_eq!(
            classify_numfmt(166, Some("[$$-409]#,##0.00")),
            NumFmtClass::Accepted(Format::Currency {
                symbol: CurrencySymbol::Dollar,
                grouping: true,
                decimals: 2
            })
        );
        assert_eq!(
            classify_numfmt(167, Some("[<100]0;[>=100]0.0")),
            NumFmtClass::Exotic,
            "a conditional switch"
        );
        assert_eq!(
            classify_numfmt(168, Some("000000000")),
            NumFmtClass::Exotic,
            "a digit mask"
        );
        assert_eq!(
            classify_numfmt(169, None),
            NumFmtClass::Exotic,
            "a custom id with no formatCode"
        );
    }

    /// `custom_codes` seeds `<numFmts>` (id >= 164); `cells` are `(ref, numFmtId, inner xml)`, where
    /// the inner xml is `<v>…</v>` for a value or `<f>…</f><v>…</v>` for a formula. Each distinct
    /// numFmtId gets its own `<cellXfs>` entry so a cell's `s` selects it.
    fn build_xlsx(custom_codes: &[(u32, &str)], cells: &[(&str, u32, &str)]) -> std::path::PathBuf {
        use std::io::Write;
        let mut ids: Vec<u32> = Vec::new();
        for (_, id, _) in cells {
            if *id != 0 && !ids.contains(id) {
                ids.push(*id);
            }
        }
        let xf_index = |id: u32| -> usize {
            if id == 0 {
                0
            } else {
                1 + ids.iter().position(|x| *x == id).unwrap()
            }
        };
        let num_fmts_xml: String = custom_codes
            .iter()
            .map(|(id, code)| format!(r#"<numFmt numFmtId="{id}" formatCode="{code}"/>"#))
            .collect();
        let xfs_xml: String = std::iter::once("<xf numFmtId=\"0\"/>".to_string())
            .chain(ids.iter().map(|id| format!(r#"<xf numFmtId="{id}"/>"#)))
            .collect();
        let styles = format!(
            r#"<styleSheet><numFmts>{num_fmts_xml}</numFmts><cellXfs>{xfs_xml}</cellXfs></styleSheet>"#
        );
        let sheet_cells: String = cells
            .iter()
            .map(|(r, id, body)| format!(r#"<c r="{r}" s="{}">{body}</c>"#, xf_index(*id)))
            .collect();
        let sheet =
            format!(r#"<worksheet><sheetData><row>{sheet_cells}</row></sheetData></worksheet>"#);
        let workbook =
            r#"<workbook><sheets><sheet name="S" sheetId="1" r:id="rId1"/></sheets></workbook>"#;
        let rels = r#"<Relationships><Relationship Id="rId1" Target="worksheets/sheet1.xml"/></Relationships>"#;
        let content_types = r#"<Types/>"#;
        let root_rels = r#"<Relationships/>"#;

        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let path = std::env::temp_dir().join(format!(
            "fsa1-xlsx-meta-{}-{nanos}.xlsx",
            std::process::id()
        ));
        let f = File::create(&path).unwrap();
        let mut zw = zip::ZipWriter::new(f);
        let opts: zip::write::FileOptions<'_, ()> = zip::write::FileOptions::default();
        for (name, body) in [
            ("[Content_Types].xml", content_types),
            ("_rels/.rels", root_rels),
            ("xl/workbook.xml", workbook),
            ("xl/_rels/workbook.xml.rels", rels),
            ("xl/styles.xml", styles.as_str()),
            ("xl/worksheets/sheet1.xml", sheet.as_str()),
        ] {
            zw.start_file(name, opts).unwrap();
            zw.write_all(body.as_bytes()).unwrap();
        }
        zw.finish().unwrap();
        path
    }

    #[test]
    fn strict_accepts_an_accepted_format_on_a_value_and_a_formula() {
        let path = build_xlsx(
            &[(164, "0.00%"), (165, "$#,##0.00"), (166, "m/d/yyyy")],
            &[
                ("A1", 164, "<v>0.125</v>"),
                ("B1", 165, "<v>1234</v>"),
                ("C1", 166, "<v>44331</v>"),
                ("D1", 164, "<f>A1*2</f><v>0.25</v>"),
            ],
        );
        assert!(
            strict_roundtrip_check(&path).is_ok(),
            "an accepted numFmt on a value or formula must pass --strict"
        );
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn strict_refuses_the_exotic_tail_on_both_a_value_and_a_formula() {
        let val = build_xlsx(
            &[(164, "[&lt;100]0;[&gt;=100]0.0")],
            &[("A1", 164, "<v>50</v>")],
        );
        let e = strict_roundtrip_check(&val).unwrap_err();
        assert_eq!(e.kind, ErrorKind::Invalid);
        assert_eq!(e.cell.as_deref(), Some("A1"));
        assert!(e.message.contains("164"), "{}", e.message);
        std::fs::remove_file(&val).ok();

        let formula = build_xlsx(&[(164, "000000000")], &[("A1", 164, "<f>1+2</f><v>3</v>")]);
        let e = strict_roundtrip_check(&formula).unwrap_err();
        assert_eq!(e.kind, ErrorKind::Invalid, "the tail refuses a formula too");
        assert_eq!(e.cell.as_deref(), Some("A1"));
        std::fs::remove_file(&formula).ok();
    }

    #[test]
    fn strict_refuses_a_non_display_exact_value_literal_but_not_a_formula() {
        let val = build_xlsx(&[(164, "0.00")], &[("A1", 164, "<v>1234.5678</v>")]);
        let e = strict_roundtrip_check(&val).unwrap_err();
        assert_eq!(e.kind, ErrorKind::Invalid);
        assert_eq!(e.cell.as_deref(), Some("A1"));
        assert!(e.message.contains("precision"), "{}", e.message);
        std::fs::remove_file(&val).ok();

        let formula = build_xlsx(
            &[(164, "0.00")],
            &[("A1", 164, "<f>10/3</f><v>3.3333333333</v>")],
        );
        assert!(
            strict_roundtrip_check(&formula).is_ok(),
            "the SAME format on a formula is never refused for precision"
        );
        std::fs::remove_file(&formula).ok();
    }

    #[test]
    fn numfmt_map_exposes_accepted_per_cell_formats() {
        let path = build_xlsx(
            &[(164, "0.00%"), (165, "[<100]0;[>=100]0.0")],
            &[
                ("A1", 164, "<v>0.125</v>"),
                ("B1", 165, "<v>50</v>"),
                ("C1", 0, "<v>7</v>"),
            ],
        );
        let map = numfmt_map(&path).unwrap();
        let sheet = map.get("S").expect("sheet S has formatted cells");
        assert_eq!(sheet.get("A1"), Some(&Format::Percent { decimals: 2 }));
        assert_eq!(sheet.get("B1"), None, "an exotic cell is absent");
        assert_eq!(sheet.get("C1"), None, "a General cell is absent");
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn numfmt_coercions_enumerates_every_non_general_cell() {
        // Unlike `numfmt_map`, the lossy path drops accepted AND exotic formats alike.
        let path = build_xlsx(
            &[(164, "0.00%"), (165, "[<100]0;[>=100]0.0")],
            &[
                ("A1", 164, "<v>0.125</v>"),
                ("B1", 165, "<v>50</v>"),
                ("C1", 14, "<v>45306</v>"),
                ("D1", 0, "<v>7</v>"),
            ],
        );
        let coerced = numfmt_coercions(&path).unwrap();
        let by_ref = |r: &str| coerced.iter().find(|c| c.cell == r);
        assert_eq!(coerced.len(), 3, "every non-General cell, General excluded");
        assert!(by_ref("D1").is_none(), "General cell is not a coercion");
        let a1 = by_ref("A1").unwrap();
        assert_eq!(a1.sheet, "S");
        assert_eq!(a1.num_fmt_id, 164);
        assert_eq!(a1.format_code.as_deref(), Some("0.00%"));
        assert_eq!(
            by_ref("B1").unwrap().format_code.as_deref(),
            Some("[<100]0;[>=100]0.0")
        );
        assert_eq!(by_ref("C1").unwrap().num_fmt_id, 14);
        assert_eq!(
            by_ref("C1").unwrap().format_code,
            None,
            "a built-in id has no custom formatCode entry"
        );
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn sheet_name_mapping_fuses_workbook_sheets_with_the_rels_targets() {
        let sheets = parse_workbook_sheets(
            r#"<workbook><sheets>
                <sheet name="Data" sheetId="1" r:id="rId1"/>
                <sheet name="Report" sheetId="2" r:id="rId2"/>
            </sheets></workbook>"#,
        )
        .unwrap();
        assert_eq!(
            sheets,
            vec![
                ("Data".to_string(), "rId1".to_string()),
                ("Report".to_string(), "rId2".to_string())
            ]
        );
        // The rels half is `resolve_target`'s, over the base the OWNING part sits at.
        assert_eq!(
            resolve_target("xl", "worksheets/sheet1.xml"),
            "xl/worksheets/sheet1.xml",
            "a relative target joins onto the owning part's directory"
        );
        assert_eq!(
            resolve_target("xl", "/xl/worksheets/sheet2.xml"),
            "xl/worksheets/sheet2.xml",
            "an absolute `/xl/...` keeps its path"
        );
        assert_eq!(resolve_target("xl", "styles.xml"), "xl/styles.xml");
        // A worksheet's own rels reach UP, which no base of `xl/` alone could resolve.
        assert_eq!(
            resolve_target("xl/worksheets", "../drawings/drawing1.xml"),
            "xl/drawings/drawing1.xml"
        );
    }

    #[test]
    fn a_defined_name_target_keeps_its_xml_entities() {
        let xml = concat!(
            r#"<?xml version="1.0"?><workbook><definedNames>"#,
            r#"<definedName name="Cmp">IF(Data!C1&lt;2,&quot;a&quot;,&quot;b&quot;)</definedName>"#,
            r#"<definedName name="Cat">&quot;x&quot;&amp;&quot;y&quot;</definedName>"#,
            r#"</definedNames></workbook>"#
        );
        let names = parse_defined_names(xml).expect("parses");
        let target = |n: &str| {
            names
                .iter()
                .find(|r| r.name == n)
                .map(|r| r.target.clone())
                .unwrap_or_default()
        };
        assert_eq!(target("Cmp"), r#"IF(Data!C1<2,"a","b")"#);
        assert_eq!(target("Cat"), r#""x"&"y""#);
    }
}
